# doc/pics/Makefile
#

SUBDIRS = 
DEVEL_HOME = ../..

EPS = bungalow.eps gear.eps gear2.eps kugel_poly.eps ship.eps wuerfel.eps \
	2_kugeln.eps gelenk.eps kugel_nurbs.eps sgs_logo.eps 

include $(DEVEL_HOME)/Makefile.incl

all: $(EPS)

clean:
	$(RM) $(EPS) *~

clean-all: clean 
