# doc/diagrams/Makefile
#

SUBDIRS = 
DEVEL_HOME = ../..

EPS= algos-gelenk.eps algos-ship.eps algos-wuerfel.eps nodes-cells-gelenk.eps \
	nodes-cells-kugel-poly.eps nodes-cells-ship.eps ram-plane.eps \
	ram-spline.eps scanline-plane.eps scanline-spline.eps \
	t-border-plane.eps t-border-spline.eps t-polygon-plane.eps \
	t-polygon-spline.eps 

include $(DEVEL_HOME)/Makefile.incl

all: $(EPS)

clean:
	$(RM) $(EPS) *~

clean-all: clean
